# Generated by Django 4.0 on 2022-01-05 21:36

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=30)),
                ('header', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('link_to_source', models.URLField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('content_creator', models.CharField(max_length=30)),
                ('content_thumbnail', models.ImageField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_content', to='auth.user')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80, verbose_name='Überschrift')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('body', models.TextField(max_length=400, verbose_name='Inhalt')),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='auth.user')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.content')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
