# Generated by Django 4.0 on 2022-01-10 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('webapp', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['uploaded_on']},
        ),
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Name', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(help_text='Maximal 42 Megabyte', upload_to='documents/name'),
        ),
    ]
