# Generated by Django 4.0 on 2022-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(help_text='Maximal 42 Megabyte', upload_to='documents/'),
        ),
    ]
