# Generated by Django 4.0 on 2022-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.CharField(choices=[('Mathe', 'Mathe'), ('Python', 'Python'), ('Betriebswirtschaftslehre', 'Betriebswirtschaftslehre'), ('Data Science', 'Data Science')], default='Mathe', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.CharField(choices=[('Mathe', 'Mathe'), ('Python', 'Python'), ('Betriebswirtschaftslehre', 'Betriebswirtschaftslehre'), ('Data Science', 'Data Science')], default='Mathe', max_length=50),
        ),
    ]
