# Generated by Django 4.0 on 2022-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_content_tags_remove_document_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('Blog', 'Blogbeitrag'), ('Video', 'Videobeitrag'), ('Internet', 'Internetseite'), ('Buch', 'Buch'), ('Sonstiges', 'Sonstiges')], default='Video', max_length=50),
        ),
    ]
