# Generated by Django 4.0 on 2022-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(help_text='Maximal 42 Megabyte', upload_to='documents'),
        ),
    ]
